### ISSUE TITLE
Instant search results as you type

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#104]
Many people have asked for this. Search results should populate as the user types a query into the search bar. We are probably efficient enough already to support this without any major optimizations. 

Implementation details / user scenario:
When the user is typing in the search bar, a search query should be made every time they type a character. If no results are found, the page should not be updated. As soon as the partial query returns a result, update the page with the returned courses. Additionally, if more than one second has passed between keystrokes, the page should be updated even if no courses are found from the last query (i.e., show that the query yielded no results). The same should happen if the user presses the enter key.

There is a chance I will have to optimize the search function for this to work well but let's give it a shot.

**Comment by copperwater** [comment]
I'm not sure this should be a global feature. For slow computers or slow connections, this will make the search a nightmare to use.

**Comment by Bad-Science** [comment]
Perhaps we should research how search engines implement this, and if they
do so globally or conditionally.

**Comment by copperwater** [comment]
Another thing to consider is that hitting the search API with a request on every character might increase load by a lot. Since there has been little discussion on this, I'm re-tagging as future and removing "easy" since we don't really want to invite external PRs implementing it.

**Comment by Bad-Science** [comment]
Closing this, as we ended up going with #55 instead.
