### ISSUE TITLE
As a student, I would like see a truncated course description by default so that I can view courses more easily

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#105]
Made this a separate issue from #90. Before building the expand feature the course description should be truncated.

**Comment by copperwater** [comment]
This is a duplicate of #74

**Comment by copperwater** [comment]
Not closing until I figure out how this is in the "Vetting" stage since evidently it has been worked on/completed.

**Comment by copperwater** [comment]
This is being closed due to its duplicate status. #74 is now the go-to issue for this.
