### ISSUE TITLE
Create Github wiki for extended documentation

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#109]
We want to go about creating a [Github wiki](https://help.github.com/articles/about-github-wikis/) for YACS. The wiki will be the main source of our extended documentation - information we should leave out of the README for conciseness, but which is still important.

Here is an incomplete list of topics that should be covered in the wiki: 

| Section | Topics |
| --- | --- |
| Using YACS | Basically a user's manual for non-technical people who just want to use YACS. High-level descriptions of how to use and navigate the application, a full list of features |
| Development environment | Setup and installation for developers, links to packages YACS depends on |
| Testing frameworks | External software we use for testing (Coveralls, Cucumber, ESLint, etc), how to configure them and use them with continuous integration |
| Production environment | Normal setup and installation, package dependencies, any special configuration for optimal performance |
| Configuration | List of configuration options, what they do, and how to set them. See issue #39. |
| API | List of all API endpoints provided by YACS, synopses, descriptions of behaviors, examples of input and output |
| Scheduler | Scheduling portion of the backend, its algorithm |
| Frontend structure | Directory structure, application.js, functions provided by the Yacs namespace, Handlebars, how 3rd party libraries are included and used |
| Catalog interface | Details on the service which extracts data from a catalog, how to configure it for different data sources |
| Update jobs | Information on the background update process, scheduling, configuration |
| Caching | Description of caching on the backend and how it works |
| Search | Search algorithm, any quirks it currently has (perhaps should just go under the API section since search is an API behavior) |

**Comment by Bad-Science** [comment]
[API](https://github.com/YACS-RCOS/yacs/wiki/API) and [Local Setup](https://github.com/YACS-RCOS/yacs/wiki/API) pages complete
