### ISSUE TITLE
As a student, I would like to see search predictions in dropdown box while typing so that I can see related terms and find quickly.

### ISSUE THREAD

**Issue by cryy1108** [YACS-RCOS/yacs#120]

**Comment by copperwater** [comment]
I think the automatic searching in #104 is kind of mutually exclusive to this, and I don't really think both should be implemented. I favor the automatic search for the following reasons:
* This adds another input element which will necessarily extend from the header bar into the main content, which could be perceived as noisy
* This necessitates adding a whole new API (search prediction based on past searches) which will contain a fair amount of backend logic, whereas automatic searching just uses the search API
* The search space is not really big or complex enough for users to need to look at other popular searches and see related terms. Most users either a) know exactly what classes they're looking for and know at least the name or number, or b) don't know what they want to take and just want to explore available courses.

Needs a more in depth design discussion with the team, but I would close this as "no plans to implement at this time".

**Comment by copperwater** [comment]
Per @Bad-Science: this was implemented over the summer, but was very messy, and requests to improve it went unanswered. The decision is to close this.
