### ISSUE TITLE
12 noon displays as 12a

### ISSUE THREAD

**Issue by akelleher** [YACS-RCOS/yacs#121]
As seen in attachment
![capture](https://cloud.githubusercontent.com/assets/3912908/17455001/9b4da006-5b78-11e6-8bdf-d43a9e325e71.PNG)

**Comment by Bad-Science** [comment]
#123 merged into staging. Will merge to master and deploy after vetting.

**Comment by Bad-Science** [comment]
<img width="1440" alt="screen shot 2016-08-07 at 1 56 01 pm" src="https://cloud.githubusercontent.com/assets/787225/17464195/c6f1b52e-5ca6-11e6-850d-aeb383cb3294.png">

Fix verified in staging (yacs.herokuapp.com). Will deploy after lunch.

**Comment by Bad-Science** [comment]
Released and deployed [v0.7.1](https://github.com/YACS-RCOS/yacs/releases/tag/v0.7.1-beta)
Fix verified in production, closing issue.

<img width="1440" alt="screen shot 2016-08-07 at 4 58 15 pm" src="https://cloud.githubusercontent.com/assets/787225/17465262/abdfbabe-5cc0-11e6-915f-d42d7412579f.png">
