### ISSUE TITLE
Use Apache solr for search

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#128]
We should use Apache solr, along with the ruby interface sunspot to provide faster and more desirable search results.

**Comment by copperwater** [comment]
Just noting that those 3 other issues above are kind of blocked by this, so it is rather important in the near future.

**Comment by rystills** [comment]
In the process of getting a sunspot server to run on windows at the moment; if I can't find a working solution soon I'll fall back to unix

**Comment by rystills** [comment]
Apache solr is now fully operational on the rystills/yacs/master, solr_docker, and solr-filtering branches, with several tweaks to improve quality of search results. It should be pulled into master once docker is ready to be deployed and solr_docker correctly runs in the docker container.

**Comment by rystills** [comment]
Re-opening this issue as solr has not yet been merged in due to complications with transitioning to docker.
