### ISSUE TITLE
Cleanup of views/schedules.js

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#139]
Some minor associated things I want to do to clean up this file:
* No semicolon on line 52
* Nomenclature and replacing of the function `show()` (this is terribly vague as to what exactly it does) as opposed to something more descriptive, like `showSchedule()`. This also goes for the functions `previous` and `next`. 
* Replace `querySelector` calls that are just querying ID elements to `getElementById`, for performance.

**Comment by elizabethfinedev** [comment]
I submitted a pull request including these fixes, hope it helps.

Changes for issue #139:
- Added in several missing semicolons
- changed show() to showSchedule()
- changed next() to nextSchedule()
- changed previous() to prevSchedule()
-changed target.querySelector calls to document.getElementById

**Comment by Bad-Science** [comment]
Thanks @elizabethfinedev ! I'll review the changes tonight :+1:

**Comment by copperwater** [comment]
As noted in that pull request, the scope of the issue now should not include the getElementById changes.

**Comment by copperwater** [comment]
#144 is now merged and this issue is finished.
