### ISSUE TITLE
Redesign layout of the course list

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#141]
We currently have a few problems with the way courses on the course list are laid out.
- The only way to "Select All" sections is by clicking somewhere on the course element that is not a section. This is not very intuitive and the CSS that does the highlighting of all sections when hovered now makes so little sense that I have disabled it in #137.
- Periods don't line up or overflow particularly gracefully if there are so many of them that they collide with the section text on the left (as happens for certain courses, like the CHEM courses). We would like to fix the width of that if possible.
- Nobody is particularly fond of the way selected sections display, and how they all coalesce into big red blobs.

This issue will be complete when the team agrees on a new design for courses in the list.

@YushYush this issue should be what you work under whenever you commit something like wireframes or mockups.

**Comment by YushYush** [comment]
Additional lower priority deliverables (for organization purposes): 

- Yacs logo (some relation to RPI logo preferable) 

- Search bar 

- potential color scheme modifications
