### ISSUE TITLE
Courses at 12 noon display as '12a'

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#155]
As the title says. This is literally a one character change. Line 37 of app/assets/javascripts/controllers/courses/helpers.js should be changed to a `>=`.

**Comment by copperwater** [comment]
Closed with #157.

**Comment by akelleher** [comment]
I still see it.
![image](https://cloud.githubusercontent.com/assets/3912908/19729506/3250a896-9b65-11e6-9912-d3a162d9feee.png)
