### ISSUE TITLE
Use schools.txt and departments.txt to control data population of schools and departments

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#16]
Currently, RPI provides us no school data whatsoever, and department names are sometimes represented in a truncated form we don't want to display (e.g. "Information Technology and Web Science" -> "Information Technlgy & Web Sci.") Also, it has a lot of departments that either don't exist, exist but for other campuses, or are never used by anyone. The proposal is to use schools.txt and departments.txt as data files to act as controls on the data coming from the parse script. This will let the YACS administrators (who could be at any college with its own data quirks) show only the departments they want and arrange them into schools however they want.

schools.txt is a tab-separated file with the school name first and any number of department codes after that. departments.txt is a tab-separated file with the department code first and the department's extended name second. When the database populates the schools and departments tables, it will use the data in these files.

Richie already implemented this now; this issue is mainly for us making it an official part of the design and documenting it.

**Comment by aosdict** [comment]
I'm currently cleaning out the top-level directory. These two files do not belong there (they should be moved somewhere in the config folder), but I can't move them until all references to them in configuration scripts can be changed to reflect the new folder.

**Comment by Bad-Science** [comment]
This should be changed to use a yaml configuration file instead of .txt files, and should ultimately live in the future catalog adapter gem

**Comment by copperwater** [comment]
Adding these to the adapter gem issue; this issue is no longer needed and is being closed.
