### ISSUE TITLE
Sort periods chronologically.

### ISSUE THREAD

**Issue by YushYush** [YACS-RCOS/yacs#186]
Students have been requesting this change for a while, and we received some feedback regarding this from our user research survey.  We attempted to implement this on the Front End, but the sorting introduced a very noticeable lags, due to multiple sort calls every time a course page was loads. 

To resolve this, period sorting should be done on the back end. Sorting should only be done when period data is modified.

**Comment by YushYush** [comment]
Existing data bases will have to have all sections sorted manually.

**Comment by copperwater** [comment]
This has been merged in as of #220.
