### ISSUE TITLE
Add flavor text to the page footer

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#207]
This was a whimsical feature of the old YACS. Its footer said "Copyright Jeff Hui. [something funny] RCOS project." 

We pretty much have the main page template ready to do this already; it simply has the flavor text hardcoded as "A Red Hat-supported". This should just involve changing the main page template and adding a Handlebars helper that randomizes the string. It probably isn't important whether it randomizes per session or per request.

The full list of flavortexts used by the old YACS can be found [here](https://github.com/jeffh/YACS/blob/master/yacs/static/angular/v4/js/controllers/FooterController.js) and is:
> 'A grass-fed, free-ranged',
> 'The best',
> 'Yet another',
> "An experimental, GMO'd",
> 'A radioactive',
> 'A zombie',
> 'An',
> 'A pizza-funded',
> 'An ice tea powered',
> 'A lone computer runs this',
> "Some guy's",
> 'A (somewhat) tested',
> 'Batteries not included in this'

**Comment by Bad-Science** [comment]
I think we should not reuse any of the old comments. Post new funny things on this thread.

**Comment by copperwater** [comment]
"A GMO-free"
"No developers were harmed in the making of this"
"A mutant"
"A longstanding"
"An" (this is fine to keep, I think)
"The second biggest"
"A Red Hat-supported"
"100% all natural"
"A third-generation"
"A heavily debugged"

Also note that the text "RCOS" should be made into a link to rcos.io.

**Comment by Bad-Science** [comment]
"Filmed on Location"
"A Y2K Compliant"
"A Vortigaunt Maintained"
"Degree Not Included in this"
"Clippy's Favorite"
"9/10 Mindless Drones Recommend this"
"Ask Your Doctor Before Using this"

**Comment by Bad-Science** [comment]
Also - The footer should be made into a View function.

**Comment by hesstruck** [comment]
an officially cursed
a shot back to back in front of a live audience 
youre all subjected to the soundscape of an
colonial by birth, cowboy by night, the enchanting,
she just doesnt make senze...
a humbled by god
over the course of your lifetime, you consume enough natural metal to say that you’ve eaten a gun.
a Pringles Newfangled Potato Chips supported
je suis 
emoticons are used by google to teach its AI. about human emotions
a vertically integrated multiverse theorized
a marx rejected
watch as shoenice downs three boxes of 
a memory of post-human society

**Comment by kburk1997** [comment]
See pull request #211

**Comment by copperwater** [comment]
Done as of #211.
