### ISSUE TITLE
Fix loading image background

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#223]
A couple of slight changes to our background color have made the loading image, when it appears, stand out with its rectangular border. This should be made transparent. Should be easy enough to do because we still have the .xcf file.

**Comment by Bad-Science** [comment]
Can you also make the image larger?

**Comment by copperwater** [comment]
If it's to be larger, it may as well get completely redone, since it's a raster image. What size were you thinking?

**Comment by Bad-Science** [comment]
liiiiiiike maybe 250 x 100 px ish? We should make it a css animation :)

**Comment by copperwater** [comment]
Done with #224.
