### ISSUE TITLE
Can view "schedules" beyond the max available

### ISSUE THREAD

**Issue by jacobspeicher** [YACS-RCOS/yacs#229]
So with the schedule I was actually looking at for next semester, I only had 1 possible schedule. I added Differential Equations, so now I had 8 schedules. I paged through all of them until I was at schedule 8/8, and then removed DiffEq. But then I was at schedule 8/1. It does the same thing adding classes back in. I took out my entire schedule and added Calc 1, so now I had 48 schedules. Added all my other classes back in while I was looking at schedule 39/48, and I ended up looking at schedule 39/1. It resets to the first schedule as soon as I start paging through the schedules again though.

**Comment by copperwater** [comment]
I believe this was solved a while back and just hasn't been in production yet. It should be part of #228, which we plan to merge in today.

**Comment by jacobspeicher** [comment]
Oh awesome, glad it already got worked out!

**Comment by Bad-Science** [comment]
@jacobspeicher #228 has been deployed. I've checked this in production and it is resolved now. Thanks for pointing this out though.
