### ISSUE TITLE
'Featured' Courses page

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#241]
We should have a page where courses that are tagged as 'featured' will be showcased. Here at RPI, these 'featured' courses will be new and special topics courses for the current semester, or any other course a professor wishes to have highlighted.

There should be a link to this page on the home page, and it should be possible to provide a URL to this page. Ultimately, this page may be able to replace the special topics courses PDF.

This will require a system for tagging courses as 'featured'. See related: https://github.com/YACS-RCOS/yacs/issues/242

Once #242 is done this should be very easy.

**Comment by marchdan** [comment]
I will pick up this task

**Comment by Bad-Science** [comment]
This issue has been moved to https://github.com/YACS-RCOS/yacs-web/issues/57
@marchdan 

The requirements of the issue have not changed.
