### ISSUE TITLE
Tag courses as 'featured'

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#242]
We need to be able to tag courses as featured for https://github.com/YACS-RCOS/yacs/issues/241. We may want to create a full-fledged tagging system, or it may be sufficient to simply add a boolean field to the courses table. If we can think of other uses for tags, we should do the former. Discuss here.

**Comment by marchdan** [comment]
I am going to pick up this issue

**Comment by Bad-Science** [comment]
@marchdan - If possible, I'd like to get this completed for the April 1st milestone https://github.com/YACS-RCOS/yacs-web/milestone/3 along with the frontend task for this https://github.com/YACS-RCOS/yacs-web/issues/57

Let me know if this is possible :)

**Comment by marchdan** [comment]
I can work to have the backend finished for sure. I will do my best for the frontend.

**Comment by Bad-Science** [comment]
Forgot to mark this as done :P Thanks again @marchdan !!
