### ISSUE TITLE
Add event for course closing

### ISSUE THREAD

**Issue by darrendlin** [YACS-RCOS/yacs#255]
US: As a developer, I would like to receive a notification that a course has closed.

A course is considered closed if all sections are closed.

**Comment by darrendlin** [comment]
People can still generally register for a different section of a course, so should a course be really considered "closed" if there are any closed sections? Wouldn't it make more sense to have the definition be "closed if ALL sections are closed"?

**Comment by Bad-Science** [comment]
@darrendlin A course is considered closed if all sections are closed.
