### ISSUE TITLE
As a student, I would like to navigate back and forward natively so I can navigate the site more effectively

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#26]
The History API should be implemented to allow the user to navigate around the site properly using the forward and back buttons. Because the site only consists of one true page and uses AJAX for all content changes, there is no history and the forward/back navigation buttons do not perform any useful purpose by default.

This is a feature of HTML5 and in order for this to work on older browsers a library such as History.js could be used.

**Comment by Bad-Science** [comment]
History states should include at least:
- courses view by department
- courses view by searches
- schedule view

**Comment by aosdict** [comment]
See here: https://developer.mozilla.org/en-US/docs/Web/API/History_API for the builtin javascript history API. If it's possible to do what we want without the HTML5 history API or History.js or both, we shouldn't use them.

**Comment by Bad-Science** [comment]
It is technically possible to do it the old HTML4 way using url fragments, but the HTML5 history api is much nicer. The History.js library uses the HTML5 history API but includes the former method as a fallback for non-HTML5 browsers

**Comment by aosdict** [comment]
Changing the milestone to General Release. I don't view forward/back navigation as an essential component of YACS; it is usable without that.

**Comment by aosdict** [comment]
Pushing this back to General Release since there are no plans to finish it at the moment. The current concept for this is to link the API string used in the request to the history state.

**Comment by Bad-Science** [comment]
I've received numerous requests for this lately

**Comment by copperwater** [comment]
Implementation of routes should implicitly solve this, according to @Bad-Science.

**Comment by copperwater** [comment]
See pull request #138.

**Comment by Bad-Science** [comment]
closed with #138
