### ISSUE TITLE
Add status to sections

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#280]
In order to support #398, we need to add a column to `sections`. This column should be a string, should allow null values, and should have null as a default value. A migration should be created to add this column.

Additionally, the `status` field should be added to the sections API in order to expose it to the frontend. This will require editing the sections jbuilder template.

**Comment by Bad-Science** [comment]
https://edgeguides.rubyonrails.org/active_record_migrations.html

**Comment by fakedestinyck** [comment]
@Bad-Science I'm not sure what is _the sections API_ and what is _the sections jbuilder template_
