### ISSUE TITLE
Create Kafka producer to write change events to Kafka topic

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#285]
Whenever a course or section record is changed, a new Kafka message should be created.

The message should be of the form `[:uuid, :record]`, where record is the JSON serialized record that changed.

This should be implented using [ActiveRecord callbacks](http://guides.rubyonrails.org/active_record_callbacks.html) to detect changes, and using the [Karafka Responders API](https://github.com/karafka/karafka/wiki/Responders) to produce messages.

TODO:
- [ ] decide whether each record type should have its own topic (probably), or how topics should be otherwise partitioned.

**Comment by bdieu178** [comment]
@Bad-Science Do you think we need to finish the data model before I can consider this task complete?
Currently I decided to build topics off of course and section changes.

**Comment by Bad-Science** [comment]
@bdieu178 Per our conversation: We do not because at this point in the pipeline we will be sending the entire record. We will need to have the event data model defined before we can implement the frontend API.

**Comment by bdieu178** [comment]
@Bad-Science Is this issue resolved to close?
