### ISSUE TITLE
ReadMe appears to be out-of-date

### ISSUE THREAD

**Issue by philipvf** [YACS-RCOS/yacs#294]
The read me for https://github.com/YACS-RCOS/yacs.git "Setting up your Dev Environment" appears to no longer refer to the correct repository. 

For example the section "Running the Application" (https://github.com/YACS-RCOS/yacs/wiki/Setting-Up-Your-Dev-Environment#running-the-application) tells users to generate SSL certificates for local use by running $ bin/yacs-generate-cert. However, this file is not present in the https://github.com/YACS-RCOS/yacs.git repository. This file is present in https://github.com/YACS-RCOS/yacs-orchestra.git. The read me for https://github.com/YACS-RCOS/yacs.git should address this.

**Comment by Bad-Science** [comment]
We've reorganized the repositories and everything is now up to date :)
