### ISSUE TITLE
Create TypeScript API Client

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#309]
This issue is to create and publish a TypeScript API Client for Yacs API V6.

The client should be created using [Graphiti Spraypaint](https://graphiti-api.github.io/graphiti/js/installation#defining-models) and published as an npm module.

The client should model the resources listed in the [API Docs](https://yacs.io/#/api/usage?id=resources). This includes the following resources:
- [x] Schools
- [x] Subjects
- [x] Terms
- [x] Courses
- [x] Listings
- [x] Sections

Please check off each box as progress is made :)

**Comment by Malorn44** [comment]
Published version: https://www.npmjs.com/package/yacs-api-client
