### ISSUE TITLE
Fix popovers in sidebar 

### ISSUE THREAD

**Issue by sydtaylo** [YACS-RCOS/yacs#341]
Cuts off at top of screen when description is large. Change so that when empty a "There is no description :(" message is displayed

**Comment by Malorn44** [comment]
Added a display message for when empty description. Going to work on fixing the description cut-off next.

**Comment by Bad-Science** [comment]
@Malorn44 seems like ng-bootstrap does support this https://github.com/ng-bootstrap/ng-bootstrap/issues/992#issuecomment-336165009

**Comment by Bad-Science** [comment]
Also, in general, I've found that ng-bootstrap has a number of undocumented features and available properties. You usually have to check the source code for a component for a complete picture of what is available.

**Comment by Bad-Science** [comment]
Resolved as of #370 thanks @Malorn44
