### ISSUE TITLE
Easy way to get CRNs submitted

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#35]
Right now, we have no way of expediting the process of getting Course Reference Numbers into the SIS registration form. We can display them on the page and the user can copy and paste them one by one and that's about it. This offers no improvement over yacs.me.

There should be a way to either copy all CRNs from a schedule and be able to paste them all at once into the fields on SIS, or to submit a POST request directly from the page that will submit the numbers for the user.

**Comment by aosdict** [comment]
It's actually quite difficult or impossible to do this without cooperation from SIS, which we probably won't get. There's no string which will auto-paste itself into multiple fields on another page.

**Comment by aosdict** [comment]
Assuming no cooperation on the Registrar's part, the best we may be able to do is put a "Copy CRNs" button or something in the schedule bar, which will copy the CRNS as tab- or newline-delimited text.

**Comment by copperwater** [comment]
Tab and newline delimited text, or any text, are known not to paste properly on SIS. A possible idea is to make CRNs as they appear in the schedule to be clickable, and a click will copy that CRN to the clipboard.

**Comment by copperwater** [comment]
If there is demand for CRNs being copyable by clicking, that should probably be its own issue and new feature. As of right now, nobody has expressed any interest in having them easily paste into SIS.

SIS isn't going to modify their page for our sake, which means that the original scope of this issue is resolved. Open a new issue if it becomes possible in the future or there actually is demand for CRN copying.
