### ISSUE TITLE
New log-in page bug

### ISSUE THREAD

**Issue by vakrao** [YACS-RCOS/yacs#350]
So I tried out the new YACS UI. 

Is the sign-in page supposed to look like what is attached?

Running on Windows 10, Firefox Quantum 63.0
![capture](https://user-images.githubusercontent.com/10600418/47806066-34824280-dd0f-11e8-8524-79a9dd722fb8.PNG)

**Comment by Bad-Science** [comment]
This is not fully implemented. We started working on this but might start over... closing this because this isn't meant to work yet though.
