### ISSUE TITLE
Sidebar should hide main content on mobile

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#371]
This is the last major issue with mobile usability in the new UI. On small viewports, the sidebar should either expand to fill the page, hiding the main content, or "pop over", hiding the content underneath. Either way, the page width on small viewports should be a maximum of 375px, even when the sidebar is collapsed. This should be verified on mobile.

**Comment by Malorn44** [comment]
Like instead of the sidebar opening to that width on mobile it just fills the whole screen and you wouldn't be able to scroll to the right?

**Comment by Bad-Science** [comment]
Yup! That's the idea
