### ISSUE TITLE
Clicking a listing's title should select it

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#377]
~Currently, clicking a listing's title does not select it. This is confusing and should be fixed ASAP. Additionally, the course should not highlight *unless* the user is hovering over an area that will select the listing if clicked.~

Current behavior: When a user clicks a course to select it, the course is not selected if all of the sections are full, because we do not by default select full sections. This is by design, the user is intended to click full sections individually to select them.

HOWEVER, we have received much feedback that this is confusing, and many users think selection is broken when they cannot click a course due to all its sections being full. To relieve this, I think we should do away with the notion of not selecting full sections.

Proposed new behavior: When a user clicks a course, all sections should be selected regardless of if they are full or open. This should avoid confusion, and prevent our users from thinking they cannot select closed sections, which they can.

Additionally, it would be nice if we showed if a section was closed in the schedule view somehow, maybe by graying out the block. But we can create a separate issue for that.

**Comment by fakedestinyck** [comment]
I think we can also show a message that says: `Your selection contains some closed sections. However, you can still select them and see them in the schedule view. But you should be aware of this situation.`

**Comment by fakedestinyck** [comment]
And what about the conflict section? Should we also let them select it?

**Comment by Bad-Science** [comment]
@fakedestinyck I think adding a warning tooltip with a message like that is a good idea. For conflicting sections... I'm a little conflicted :P I'd like to say just select them all, but I want to avoid the experience of picking something, going to the schedule page, and not seeing any schedules. What if we also let them select the conflicted sections, but showed a second warning tooltip saying that either some of the sections in the course conflict, or all of them do. Does that make sense?

**Comment by fakedestinyck** [comment]
@Bad-Science Ok I'll do like that, and tell you if I have any further questions.
