### ISSUE TITLE
Sidebar should be more visible when collapsed

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#393]
Currently, when the sidebar is collapsed only a small arrow is show, and we have received feedback that this is very hard to notice and not intuitive. We need the sidebar to always have a presence on the page, and interaction with it should be intuitive. On mobile viewports, this should probably be worked into the navbar, since we can't afford to lose the horizontal space. On desktop the collapsed sidebar could be toggleable from some element on the side of the page, or from the navbar.

**Comment by Malorn44** [comment]
Maybe, we could have something like this:

(this is just a mockup. I didn't make any changes)

![screenshot_2019-01-26 yacs](https://user-images.githubusercontent.com/11843425/51790700-cfe84f80-2166-11e9-8a90-84547c50397f.png)

**Comment by Bad-Science** [comment]
Hey @Malorn44! Thanks for making the mockup. I think this is a good start.

My main criticism would be that it looks a bit awkward where the sidebar meets the navbar, and the footer as well. Maybe it should be less tall, like a drawer or something.

cc @sydtaylo 

Some indicator like highlighting is definitely a good idea.

**Comment by sydtaylo** [comment]
I think it might be good to make it very pale grey. And use a hamburger icon instead of the arrow and put it at the top instead of in the middle. But I really do like the bar running the whole height of the screen.

**Comment by Malorn44** [comment]
I have issue with the hamburger icon since we are already using that for the navbar when width is too small. I feel it would be confusing for people.

**Comment by Malorn44** [comment]
1. Selecting a course when sidebar was previously empty should show a small "ding" next to the sidebar button to promt the user to open it.

2. Sidebar shouldn't displace other elements if there is enough screen width

Just something to think about.

**Comment by Malorn44** [comment]
So is anyone currently working on this? It says status:inprogress but no one isn't assigned.

**Comment by Bad-Science** [comment]
@Malorn44 Nope! Needs to be worked on

**Comment by Malorn44** [comment]
Things are happening.
![image](https://user-images.githubusercontent.com/11843425/52547995-03e38780-2d99-11e9-8e4e-2e63fde1d721.png)
