### ISSUE TITLE
Create UI for selecting active term

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#394]
We need a way for users of yacs-web to select what term they would like to view courses from. The API already supports the necessary queries. We just need to design and build a UI for viewing and selecting them, and create a simple angular service for storing the selected term.

When a given term is selected, only listings from that term should be displayed. We should discuss how and if this should affect search, and if there are any cases where we want to show listings from multiple terms.

**Comment by Bad-Science** [comment]
Hi @CerulanLumina ! Thanks for picking this up.

I do think the navigation buttons look pretty clean, and being able to simply click forward and backward seems like it would be convenient. Although I'm not quite sure how the drop-down would fit in or mix with the left/right navigation.

We also need to think about how this will play on mobile. The navbar collapses for `xs`/`sm` viewports, so it may be unwieldy in that case. Having said that, it doesn't have to work or look exactly the same on desktop as it does on mobile.

I also think we should consider putting this in the sidebar, since we have more vertical space to work with there (or perhaps expanding the navbar to be more robust in general? although then we may make the mobile views more complicated). I think @sydtaylo and I had some discussions about this a while back but I can't remember where we left off.

**Comment by sydtaylo** [comment]
I love the idea of having the left and right navigation arrows, but was originally just going to do a drop down and if one ends up needing to be picked I think the drop down is more important. The placement on the screen is good.

**Comment by CerulanLumina** [comment]
Finally making some progress on this, I went with the original design after confirming it works on mobile, hope to have it done sometime next week. 

Sorry for the delay!

**Comment by CerulanLumina** [comment]
This will be extended to include the ability to set a writable term via a new ui element, while other terms will be read-only (unable to select terms). When viewing a term that is not the active one, the button may be clicked to set the term as active and allowing it to have selectable sections, but clearing the selected terms in the process.

**Comment by CerulanLumina** [comment]
I'm having a little trouble coming up with the UI for this extension -- there isn't much space in the header, so the button would have to be likely a single icon. However, indicating to the user that the term they have selected is not writable is tricky, especially from just a single icon. One possible solution I thought of was to place a notice in the sidebar explicitly telling the user what was going on. I would like input on this.

**Comment by Bad-Science** [comment]
Closed as of #424 Thanks @CerulanLumina !!!
