### ISSUE TITLE
Redesign schools view

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#401]
**Is your feature request related to a problem? Please describe.**
The Schools view (the Yacs homepage) works fine, but with the updates we have made to the other views it is looking a little dated.

**Describe the solution you'd like**
Open to any ideas! The new design should be consistent with the other recent design changes, but exactly how it should look is up for discussion!

**Describe alternatives you've considered**
We could certainly re-use the "card" style we use for listings now, but this is not a requirement, and I'm not sure how good it would look. We also aren't limited to the small amount of information that is currently on there. Perhaps it would be nice to show the number of listings available in each subject, for example.

**Additional context**
What it looks like now:
![image](https://user-images.githubusercontent.com/787225/52169437-4a384700-2706-11e9-985c-8ad65dca8808.png)

**Comment by Malorn44** [comment]
![image](https://user-images.githubusercontent.com/11843425/52866419-9a52d880-310c-11e9-988d-cde486e57d99.png)
So I don't personally like how this looks but I was just screwing around to make something to help bring up discussion.

**Comment by Bad-Science** [comment]
@Malorn44 some specific things I think don't look good to guide future :
- Lots of colour / inverted text
- Rounded corners. We are pretty consistent everywhere else with hard edges
- This is basically the same thing as before but covered in ketchup

Things I do like:
- Displaying the schools as 'cards'

Overall, we should be consistent with the design language we have established with the courses redesign.
