### ISSUE TITLE
Sidebar content should scroll independently from the rest of the page

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#402]
**Is your feature request related to a problem? Please describe.**
When a user selects a large number of courses, the sidebar content becomes very long. Currently, this just causes the page height to increase, forcing the user to scroll the entire page to view and interact with the content towards the bottom of the sidebar.

**Describe the solution you'd like**
The sidebar should scroll independently from the rest of the page. It should also have a fixed height equal to the height of the page.

**Describe alternatives you've considered**
None, but open to suggestions.

**Additional context**
This was reported as usability issue during the HCI testing last fall.

**Comment by Malorn44** [comment]
Okay, I got a scroll bar working with the sidebar and made it so the sidebar doesn't increase the height of the page. Still trying to figure out how to make it so that it scrolls independently.
