### ISSUE TITLE
404 Error when clicking Project on https://yacs.io

### ISSUE THREAD

**Issue by Alfriadox** [YACS-RCOS/yacs#410]
**Describe the bug**
There is what appears to be a GitHub 404 error.

**To Reproduce**
1. Go to [yacs.io](https://yacs.io)
2. Click on Projects in the top right corner.
4. 404

**Expected behavior**
I expect it to bring me [here](https://github.com/YACS-RCOS/yacs).
The GitHub link is already up there though, so I am not exactly sure where it really *should* go.

**Screenshots**
See [here](https://github.com/orgs/YACS-RCOS/projects/3/)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser firefox
 - Version don't know

**Comment by BrianHotopp** [comment]
Can someone assign me this issue? This issue was created on the wrong repo. I created a new issue on the correct repo. Can someone close this issue and take a look at the other one?

**Comment by colegregory** [comment]
Moved this issue to YACS-RCOS/docs:
[404 Error when clicking Project on https://yacs.io #27](https://github.com/YACS-RCOS/docs/issues/27)
