### ISSUE TITLE
Re-add course title tooltip to periods on the schedule view

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#42]
Currently, the schedule generates one guaranteed line of text for each period - the department code, course number, section number, and class type. I'd like to add course titles for periods that are long enough to hold them. These course titles are already exposed in the API and are parsed into the period objects in yacs-main.js.

The problem is that course titles can get quite lengthy and there's no good way to estimate how many lines they will take up at our font size and width. (I tested it and found that the longest string of "m" that will fit on one line is only 10 characters long, but of course the average amount of characters per line is much higher.) The general formula for now is (number of lines) = (number of full half-hours in the period), which is already being calculated.

Setting course elements to overflow:hidden allows the text to be horizontally cut off on the last line, so I doubt that it's an acceptable solution.

**Comment by aosdict** [comment]
Am wavering on the overflow:hidden thing. It would be an elegant *solution*, but it still doesn't look great. But it might be an acceptable way to resolve it if we can't find a way to do it mathematically with enough accuracy.

**Comment by aosdict** [comment]
For the RPI release, we're going to use overflow:hidden and apply a title attribute to all of those periods that will bring up a tooltip showing the whole course name.

**Comment by aosdict** [comment]
Title attribute is in place and overflow is now hidden. I've been doing some research into this and it appears there is no elegant CSS way to truncate the text with or without an ellipsis (there are a couple third-party libraries out there that do it, but that's it.) I'm removing this from the RPI Release milestone because we're done with what we wanted to do for now.

**Comment by copperwater** [comment]
The redesigned deselection list could also include course titles. That is not related to this, and the tooltips remain an outstanding issue (they were removed with the new schedule library).

**Comment by copperwater** [comment]
This is no longer a "problematic" issue, removing tag

**Comment by copperwater** [comment]
Closed by #140.
