### ISSUE TITLE
Searching for a prefix gives different results than the prefix page

### ISSUE THREAD

**Issue by galengold** [YACS-RCOS/yacs#426]
**Describe the bug**
Using the search bar to search for a department prefix returns different results and orders them in a non-intuitive (to the user) way, compared to the listing of all courses in prefix.

**To Reproduce**
1. Go to the search bar.
2. Type in a prefix, like "ECSE"
3. Compare the search results to the listings from clicking the same prefix's link on the main page

**Expected behavior**
The search results should match the listing on the prefix page.

Thought: maybe have a set of special case search terms, where if you search a prefix, it goes to the prefix listing, same as clicking to it from the main page.

**Screenshots**
https://imgur.com/a/sGL3vZ6

**Desktop (please complete the following information):**
 - OS: any
 - Browser: Any
 - Version: 0.9

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: 0.9

**Comment by kevinb5617** [comment]
This issue was created for version 0.9 and on version 1.2 the search results for a class prefix matches the list from the homepage menu.
