### ISSUE TITLE
Incorrectly marked conflicts

### ISSUE THREAD

**Issue by galengold** [YACS-RCOS/yacs#436]
**Describe the bug**
When selecting 2 courses, YACS determined that they were conflicting when they are not.

**To Reproduce**
1. In the 0.12 demo (rpi.yacs.io) for F19
2. Add ECSE 4520 to the schedule
3. Add ECSE 4530 to the schedule

**Expected behavior**
Normal YACS behavior, a schedule is generated for the two courses, with blocks 10a-11:20a on MTRF.

**Screenshots**
https://cdn.discordapp.com/attachments/405543428290510848/565169095167705126/unknown.png

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 66.0.2

**Comment by Malorn44** [comment]
The code for this starts here https://github.com/YACS-RCOS/yacs/blob/master/core/app/models/section.rb#L20, which is called whenever a section is created/updated. The conflicts for a particular section are generated in the SQL procedure here https://github.com/YACS-RCOS/yacs/blob/master/core/db/structure.sql

**Comment by colegregory** [comment]
https://github.com/YACS-RCOS/yacs/blob/ca702a727342018a6c1a6a53774e0fec33c8da06/core/db/structure.sql#L56

Should be `IF (this_section_period->>'day' = other_section_period->>'day' `
For ECSE 4520 and ECSE 4530, it's comparing blocks regardless of day.

**Comment by Bad-Science** [comment]
@colegregory Yup that'll do it! Go ahead and open a PR if you want :)

**Comment by Bad-Science** [comment]
This has been resolved as of #439. We will have to re-generate conflicts on the site now that the procedure has been fixed.
