### ISSUE TITLE
Optimize automated seat count updating

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#46]
derived from https://github.com/aosdict/yacs/issues/23 

Automated seat count updating has been implemented but should be optimized. taken from #23 , "A suggested approach is to poll this file every minute or so and store it in memory. On each subsequent poll, diff the new file with the one previously stored, and update sections corresponding to changed lines. (obviously) then update the locally stored copy. The records corresponding to the changes seat counts should then be updated in the database."

**Comment by aosdict** [comment]
Do you think this is important enough to put it under General Release?

**Comment by Bad-Science** [comment]
I suppose it might not be.

**Comment by copperwater** [comment]
This will be done when the data updating is rewritten completely in the near future. Since there are consequently no plans to do this on the existent updater, I am closing this.
