### ISSUE TITLE
Add a "no results" page on search

### ISSUE THREAD

**Issue by jputlock** [YACS-RCOS/yacs#466]
Searching something that is not found just shows a blank page.

**Comment by christinekoul** [comment]
![Screenshot from 2019-08-02 13-29-40](https://user-images.githubusercontent.com/46358805/62387957-16f63980-b52a-11e9-99cc-20711bd4a5e1.png)

Here's what I have so far for the page. Suggestions/critiques are welcome!

**Comment by Malorn44** [comment]
looks pretty good to me so far

**Comment by marchdan** [comment]
#490 Was submitted and approved to integrate this functionality. Linking is still in progress by @123joshuawu
