### ISSUE TITLE
Phantom JS Link is Down

### ISSUE THREAD

**Issue by NicholasLYang** [YACS-RCOS/yacs#485]
**Describe the bug**
Running `bin/yacs-prepare-development` fails with an error of:
```
ERROR: Service 'core' failed to build: The command '/bin/sh -c apt-get install -y vim git wget libfreetype6 libfontconfig &&   wget -q -O /tmp/phantomjs-$PHANTOMJS_VERSION http://rpi.edu/~robinm8/phantomjs &&   mv /tmp/phantomjs-$PHANTOMJS_VERSION /usr/bin/phantomjs &&   chmod +x /usr/bin/phantomjs' returned a non-zero code: 8
```

This is due to the Dockerfile attempting to pull what I assume is the phantomjs binary from 
`http://rpi.edu/~robinm8/phantomjs` (not HTTPS!). That link no longer works.

**To Reproduce**
1. Clone repo
2. Install docker, etc.
3. Run `bin/yacs-prepare-development`

**Expected behavior**
Set up script runs without failure

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox (not that this matters)
 - Version: 69.0b12

**Comment by Bad-Science** [comment]
Thanks for the heads up @NicholasLYang 

Opened https://github.com/YACS-RCOS/yacs/pull/488 to remove this dependency. We don't really need it any more and it is deprecated anyway.

**Comment by NicholasLYang** [comment]
Sounds good! I appreciate the scripts for setting up the environments. Makes my life a little easier haha
