### ISSUE TITLE
Schedule Doesn't Populate Properly

### ISSUE THREAD

**Issue by bsakai2000** [YACS-RCOS/yacs#499]
**Describe the bug**
Schedule displays a spinning loading symbol instead of populating the information requested

**To Reproduce**
Add some classes to your schedule, click the schedule tab

**Expected behavior**
Schedule should populate with possible combinations of classes

**Screenshots**
None but here are the console logs
`ERROR Error: "Uncaught (in promise): Error: Server Error
ResponseError@https://yacs.cs.rpi.edu/vendor.js:128950:28
./node_modules/spraypaint/lib-esm/request.js/Request.prototype._handleResponse/</<@https://yacs.cs.rpi.edu/vendor.js:128913:35
step@https://yacs.cs.rpi.edu/vendor.js:130347:23
verb/<@https://yacs.cs.rpi.edu/vendor.js:130328:53
fulfilled@https://yacs.cs.rpi.edu/vendor.js:130318:58
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@https://yacs.cs.rpi.edu/polyfills.js:3288:26
onInvoke@https://yacs.cs.rpi.edu/vendor.js:42608:33
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@https://yacs.cs.rpi.edu/polyfills.js:3287:52
./node_modules/zone.js/dist/zone.js/</Zone.prototype.run@https://yacs.cs.rpi.edu/polyfills.js:3047:43
scheduleResolveOrReject/<@https://yacs.cs.rpi.edu/polyfills.js:3786:34
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@https://yacs.cs.rpi.edu/polyfills.js:3320:31
onInvokeTask@https://yacs.cs.rpi.edu/vendor.js:42599:33
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@https://yacs.cs.rpi.edu/polyfills.js:3319:60
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@https://yacs.cs.rpi.edu/polyfills.js:3092:47
drainMicroTaskQueue@https://yacs.cs.rpi.edu/polyfills.js:3498:35
"
    Angular 8
        resolvePromise
        resolvePromise
        scheduleResolveOrReject
        invokeTask
        onInvokeTask
        invokeTask
        runTask
        drainMicroTaskQueue`

**Desktop (please complete the following information):**
 - Ubuntu 19.10
 - Firefox 69.0.3

But similar issue appears on Chrome on Windows 10

**Additional context**
None

**Comment by bobmayuze** [comment]
We noticed it and are still looking at it. It might be the issue of the combination are still getting generated

**Comment by bobmayuze** [comment]
It is fixed not
