### ISSUE TITLE
Implement a general school-balancing algorithm for the homepage

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#53]
The XML API, as we know, does not consider the amount of columns of schools that the client can render and it is left to the frontend to determine how to fill the columns. The current algorithm for filling these is to sort them by "height" (roughly calculated as the number of departments in a school plus one on the assumption that departments will all be the same height and the school heading is around that height), and then iterate over the columns, placing the largest remaining school there, and looping back to the left column. The shortcomings of this approach are evident in how RPI's schools render in two columns: the left column is substantially taller than the right.

Optimally, there should be an algorithm in place which, given the array of school heights and number of columns to fill, returns data that places the schools in the columns such that their heights are as even as possible.

**Comment by aosdict** [comment]
Made a greedy algorithm that works well in almost all cases:
```
Parameters:
c​ = Number of columns
​source​ = array of estimated "heights" of each school (this estimation is 1 + the number of departments)

Extra storage needed:
​totals​ - An array ​c​ long that stores total heights, all initialized to 0; [0, 0, ...]
​actual​ - An array ​c​ long that stores arrays containing the indices of the schools, all initialized to empty arrays [ [], [], ... ]

Algorithm:
Sort ​source​ from greatest to least
For each ​height​ in ​source​:
    ​targetcol​ = the column that has the smallest value in ​totals​ (take the leftmost if there is a tie)
    ​totals​[​targetcol​] += ​height​
    ​actual​[​targetcol​].append(this school index)
return actual
```
I'll implement this soon.

**Comment by aosdict** [comment]
Sorry. I will NOT be implementing this till we start using frontend frameworks, since the current code contains both jQuery and direct DOM manipulation, and I don't want to rewrite it and then throw it away shortly after.

**Comment by aosdict** [comment]
This is very related to #76, though this can be implemented without any sort of priority of the schools.

**Comment by copperwater** [comment]
Not sure if our use of columns makes this issue irrelevant, since columns do attempt to balance as best as possible. I believe when I started using columns that was my intent.

**Comment by copperwater** [comment]
Closing this, since columns supercede this issue.
