### ISSUE TITLE
Phase out jQuery calls

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#55]
Richie pointed out that our jQuery calls are nearly all stuff that can be replaced by modern native Javascript calls, such as:
* document.getElementById
* document.getElementsByTagName
* document.getElementsByClassName
* document.querySelector
* document.querySelectorAll

Nearly all of the current jQuery calls can easily be replaced with these alternatives, since we're pretty much only using selectors and iterating over selected groups. The one exception is that we rely on the call `$('div#content').empty()` to get rid of all event handlers in the main content div, which prevents page slowdown over time. Replacing that call will need to be examined closely, and it may indeed warrant its own issue.

The goal of this issue is: Replace the extant jQuery calls with native JS ones, while not adding in any other ones. Once there are no '$' characters in any of our Javascript code, this issue can be closed.

**Comment by aosdict** [comment]
I'd make it a priority to go for the jQuery calls in the course list formatting first. Those affect the greatest quantity of data.

**Comment by aosdict** [comment]
Note: when rewriting the code around the $('course').click() handler, alter the logic so that it deselects all courses when all courses are selected *or closed*.

**Comment by aosdict** [comment]
I *think* I can replace the .empty() call with something as simple as `nsYacs.contentContainer.innerHTML = null;` but this should still be done last, because .empty() also cleans up all internal jQuery data on the children. Thus it shouldn't be replaced while jQuery functions are being run on the children.

**Comment by Bad-Science** [comment]
note: jquery is not present in any new front end code

**Comment by copperwater** [comment]
Closed #86 last night because it's been considered done for a while. jQuery is still absent from the code so this can be closed.
