### ISSUE TITLE
Yacs does not load as of 6/12

### ISSUE THREAD

**Issue by cjmaria** [YACS-RCOS/yacs#558]
YACS does not advance past the rotating circle screen.  The header  and search bar appears, but no courses are visible.

I attempted to connect to https://yacs.cs.rpi.edu/ on the latest version of Firefox, Safari, and Chrome with no success from two different internet providers..

**Comment by 123joshuawu** [comment]
Thanks for the feedback! YACS is currently down, we're working on a fix and we'll let you know as soon as the issue is resolved.

**Comment by 123joshuawu** [comment]
The issue has been fixed and YACS is back up! Closing for now, feel free to reopen or make a new issue if it persists.
Thank you for your feedback!
