### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#63]
We need to do a load test on the server, our temporary Heroku one if a CS department one isn't forthcoming, to make sure the backend is ready to handle the load of hundreds of students connecting and making requests at once.
Since none of us appear to be experienced in writing load tests, we will need to research how these are done.
This is **absolutely necessary** for the RPI release. If it turns out that it can't handle the load, we will have to go back and figure out how to improve it so that it can.

**Comment by Bad-Science** [comment]
#28 will make all the difference in terms of performance. if we cannot withstand the load we know what to do.

**Comment by wyattkroemer** [comment]
Currently working on trying to use Apache JMeter (https://jmeter.apache.org/) for load testing.

**Comment by Bad-Science** [comment]
Throwing this into General Release. see #28

**Comment by copperwater** [comment]
Never finished. Decided we didn't need it.
