### ISSUE TITLE
Method of limiting course descriptions by default 

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#74]
Course descriptions are long and take up quite a large amount of page space (for 1-section courses, the description is often taller than the course heading and section combined). These should probably be limited by default and only expandable when the user indicates they want the full text.
A proposed way of doing this: set the description to non-wrapping, forcing it to be limited to one line, and add an ellipsis button at the right that when clicked removes both it and the non-wrapping style. That would be irreversible but would reset when the page reloaded (unless we wanted to do something funky with the cookie).

**Comment by aosdict** [comment]
Also see #90

**Comment by copperwater** [comment]
Done by Haoxin, but we want to reimplement it. See pull request #115.

**Comment by copperwater** [comment]
Don't know why the future tag is on here since it's done and I'll be opening a PR shortly. Removing that.
