### ISSUE TITLE
(Admin) Optionally have schools in the departments API returned in a fixed order

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#76]
With the new balancing algorithm that is coming soon, there are some possible pitfalls if it just runs on all schools without concern for what should appear first. One example that appears in RPI's data with two columns is that the HASS school, having the most departments, will always be placed in the top of the leftmost column, pushing the School of Engineering down. This is bad since there will probably be more users trying to navigate to engineering departments than HASS departments.
The proposal is to have configuration options available that prioritize groups of schools. Each priority group will be placed in using the balancing algorithm on the columns and whatever schools have already been placed there. An example for RPI would be: 

| School | Priority |
| --- | --- |
| Engineering | 0 |
| Science | 0 |
| HASS | 1 |
| ITWS | 1 |
| Architecture | 1 |
| Management | 1 |
| Other | 2 |

Richie thinks this should be done with frontend templates, so it will wait until they are at least in progress.

**Comment by aosdict** [comment]
If we end up not using a balancing algorithm and using the existing CSS columns, this issue should instead focus on some sort of config file that simply defines the intended order of schools. In either case, this will involve at least a little backend work so I am adding that tag.

**Comment by copperwater** [comment]
I think #53 is close to being resolved, and if it is resolved by retaining the CSS columns then the Frontend tag can be removed. In that case, this issue might diminish to configuring the order of the schools to appear in the columns, since you can't really control where the columns will break the list and ensure that the highest priority schools appear in the top of every column.

**Comment by copperwater** [comment]
#53 is closed. Removing the Frontend tag. This should be enforceable by using a yaml file on the backend, according to @Bad-Science.
