### ISSUE TITLE
Schedule image export

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#8]
Users should be able to save their schedule to a PDF file or print it directly from the browser. Different from using normal browser print function because it shouldn't print the header bar or anything else on the page except maybe a text list of courses and times.

This is something that should be done well after YACS is launched and working properly, far in the future.

**Comment by copperwater** [comment]
Modifying the scope of the issue. Nobody wants to save to PDF or print, so we are planning to have an image exporter instead. The recommended library is https://github.com/tsayen/dom-to-image, but it could be something else.

**Comment by Bad-Science** [comment]
Spring cleaning! This has been superseded by yacs-rcos/yacs-web#12
