### ISSUE TITLE
Improve course update procedure

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#84]
The method Catalog::RpiAdapter#update_courses needs to be improved. The issue is that it will update section records regardless of whether or not any actual changes have occurred in the data. This causes the caches for the courses xml views to expire prematurely, which would result in a performance hit if this procedure were run frequently. The records should only be updated as needed.

**Comment by Bad-Science** [comment]
The procedure should also be able to remove courses and sections that no longer exist.

**Comment by copperwater** [comment]
We plan to throw away the old catalog adapter code and do it in a way that's easier to adapt to individual schools; see #168. The ImproveCourseUpdateProcedure84 branch is being maintained only for reference in creating that gem. This issue, in its original scope, will not be completed.
