### ISSUE TITLE
Refactor frontend code base to use Handlebars.js templates

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#86]
In an effort to clean up the very messy Javascript code, we are going to move to the Handlebars framework and switch everything from the XML API to JSON. This will involve writing templates and various small helper functions. Handlebars doesn't appear to support event listeners by default so the code for those will remain mostly unchanged for now.

**Comment by Bad-Science** [comment]
Mostly there except for schedules view

**Comment by copperwater** [comment]
We have decided not to really use templates for the schedule itself anymore. There is a schedules.hbs file which does template the schedule page, but it leaves the actual schedule-content div empty and lets the other javascript library generate it.

Closing this because as far as I can tell this is already vetted and deployed on production.
